### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by dzyla** [paulscherrerinstitute/cbf#10]
Hello,

I tried to install this library but:

`C:\Python35>.\Scripts\pip3.exe install cbf
Collecting cbf
  Using cached https://files.pythonhosted.org/packages/7b/9f/33002159c79e0406168d0cbc50d229ead2a10d2851dcaf5f0cae071a789f/cbf-1.1.3.tar.gz
Installing collected packages: cbf
  Running setup.py install for cbf ... error
    Complete output from command c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-we_suyj3\\cbf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-record-t07pj4k7\install-record.txt --single-version-externally-managed --compile:
    WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    copying .\cbf.py -> build\lib.win-amd64-3.5
    copying .\setup.py -> build\lib.win-amd64-3.5
    copying .\__init__.py -> build\lib.win-amd64-3.5
    running build_ext
    building 'cbf_c' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python35\include -Ic:\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpsrc/cbf.cpp /Fobuild\temp.win-amd64-3.5\Release\src/cbf.obj -lstdc++ -O3 -Wall -W -Wundef -DVERSION="1.1.3" -DCBF_VERSION="0.0.1"
    cl : Command line error D8004 : '/W' requires an argument
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-we_suyj3\\cbf\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-record-t07pj4k7\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-we_suyj3\cbf\`

happened. Any idea how to fix that?

**Comment by simongregorebner** [comment]
It seems you try to install the package on Windows, right?
We haven't tested the whole package/code on windows yet.

we will try to get hold of a windows machine and try to reproduce this (but this will not happen very soon I guess)

**Comment by simongregorebner** [comment]
soon is ... unbelievable long ... sorry
I guess this is outdated ...
