### ISSUE TITLE
Include the complete format name in the README.

### ISSUE THREAD

**Issue by mjstahlberg** [paulscherrerinstitute/cbf#13]
I came here looking for a library about the Conic Benchmark Format (see [here](https://cblib.zib.de/) or [here](https://docs.mosek.com/9.0/capi/cbf-format.html)) used in mathematical optimization. You should mention in `Readme.md` that this library is about the Crystallographic Binary Format to avoid confusion.

**Comment by simongregorebner** [comment]
@Viech Thanks for the hint! I added the hint that cbf in this context stands for Crystallographic Binary Format to the Readme
Hope people get less confused now...
