### ISSUE TITLE
Switch conda packaging to reccommended - no egg file 

### ISSUE THREAD

**Issue by davidslac** [paulscherrerinstitute/cbf#8]
I've been looking into adding cbf to the conda environments we maintain at LCLS, @chucki82 is using them locally (some work on this https://github.com/slaclab/anarel-manage/issues/4)

However, in your conda recipe build.sh, would it be possible to switch from

`python setup.py install
`
to 

`python setup.py install --single-version-externally-managed --record=record.txt
`
Right now, the install creates a .pth file and a egg file - it is not that these are wrong, but they are not recommended for conda environment management. I started a discussion here

https://groups.google.com/a/continuum.io/forum/#!topic/conda/XFN2Lhm1ECE

to get some clarification about it. I think egg files are discouraged because it is harder to track things like file collisions between packages - the recommended way allows conda to track the packages better, I think.

**Comment by simongregorebner** [comment]
Thanks a lot for the input and hint!
The new version 1.1.2 with the fix should now be available on anaconda.org
